let datos=[];let graficos={};const formato=new Intl.NumberFormat("es-PE");
Papa.parse("datos.csv",{download:true,header:true,dynamicTyping:true,complete:function(r){datos=r.data.filter(d=>d.fecha);cargarFiltros();renderizar();}});
["filtroMes","filtroCentro","filtroServicio"].forEach(id=>document.getElementById(id).addEventListener("change",renderizar));
document.getElementById("btnLimpiar").addEventListener("click",()=>{filtroMes.value="TODOS";filtroCentro.value="TODOS";filtroServicio.value="TODOS";renderizar();});
function cargarFiltros(){llenarSelect("filtroMes",unicos(datos.map(d=>d.mes)));llenarSelect("filtroCentro",unicos(datos.map(d=>d.establecimiento)));llenarSelect("filtroServicio",unicos(datos.map(d=>d.servicio)));}
function llenarSelect(id,valores){const s=document.getElementById(id);valores.forEach(v=>{const o=document.createElement("option");o.value=v;o.textContent=v;s.appendChild(o);});}
function unicos(lista){return[...new Set(lista)].sort();}
function filtrarDatos(){return datos.filter(d=>(filtroMes.value==="TODOS"||d.mes===filtroMes.value)&&(filtroCentro.value==="TODOS"||d.establecimiento===filtroCentro.value)&&(filtroServicio.value==="TODOS"||d.servicio===filtroServicio.value));}
function sumar(lista,campo){return lista.reduce((t,i)=>t+Number(i[campo]||0),0);}
function agrupar(lista,campo){return lista.reduce((a,i)=>{a[i[campo]]=a[i[campo]]||[];a[i[campo]].push(i);return a;},{});}
function calcularEstado(c){if(c>=90)return{texto:"Bueno",clase:"verde"};if(c>=70)return{texto:"Regular",clase:"amarillo"};return{texto:"Crítico",clase:"rojo"};}
function renderizar(){const data=filtrarDatos();const at=sumar(data,"atenciones");const mt=sumar(data,"meta");const er=sumar(data,"errores");const cu=mt>0?(at/mt)*100:0;const br=Math.max(mt-at,0);const es=calcularEstado(cu);kpiAtenciones.textContent=formato.format(at);kpiMeta.textContent=formato.format(mt);kpiCumplimiento.textContent=cu.toFixed(1)+"%";kpiBrecha.textContent=formato.format(br);kpiErrores.textContent=formato.format(er);estadoGlobal.textContent=es.texto;renderGraficoTendencia(data);renderGraficoServicio(data);renderGraficoCentro(data);renderAlertas(data);renderTabla(data);}
function crearGrafico(id,tipo,labels,datasets,opciones={}){if(graficos[id])graficos[id].destroy();graficos[id]=new Chart(document.getElementById(id),{type:tipo,data:{labels,datasets},options:{responsive:true,plugins:{legend:{labels:{color:"#e5e7eb"}}},scales:tipo==="doughnut"?{}:{x:{ticks:{color:"#cbd5e1"},grid:{color:"#1e293b"}},y:{ticks:{color:"#cbd5e1"},grid:{color:"#1e293b"}}},...opciones}});}
function renderGraficoTendencia(data){const g=agrupar(data,"mes");const labels=Object.keys(g).sort();crearGrafico("chartTendencia","line",labels,[{label:"Atenciones",data:labels.map(m=>sumar(g[m],"atenciones")),tension:.35}]);}
function renderGraficoServicio(data){const g=agrupar(data,"servicio");const labels=Object.keys(g);crearGrafico("chartServicio","doughnut",labels,[{label:"Atenciones",data:labels.map(s=>sumar(g[s],"atenciones"))}]);}
function renderGraficoCentro(data){const g=agrupar(data,"establecimiento");const lista=Object.keys(g).map(c=>{const at=sumar(g[c],"atenciones");const mt=sumar(g[c],"meta");return{centro:c,cumplimiento:mt>0?(at/mt)*100:0};}).sort((a,b)=>b.cumplimiento-a.cumplimiento);crearGrafico("chartCentro","bar",lista.map(x=>x.centro),[{label:"Cumplimiento %",data:lista.map(x=>x.cumplimiento.toFixed(1))}]);}
function renderAlertas(data){const g=agrupar(data,"establecimiento");const lista=Object.keys(g).map(c=>{const at=sumar(g[c],"atenciones");const mt=sumar(g[c],"meta");const er=sumar(g[c],"errores");const cu=mt>0?(at/mt)*100:0;return{centro:c,errores:er,cumplimiento:cu};}).sort((a,b)=>a.cumplimiento-b.cumplimiento).slice(0,5);alertas.innerHTML=lista.map(x=>{const e=calcularEstado(x.cumplimiento);return`<div class="alerta ${e.clase}"><strong>${x.centro}</strong><br>Cumplimiento: ${x.cumplimiento.toFixed(1)}% | Errores: ${x.errores}<br><small>Recomendación IA: reforzar seguimiento operativo, revisar calidad del registro y contrastar meta vs producción.</small></div>`;}).join("");}
function renderTabla(data){tabla.innerHTML=data.slice(0,400).map(d=>{const cu=d.meta>0?(d.atenciones/d.meta)*100:0;const e=calcularEstado(cu);return`<tr><td>${d.fecha}</td><td>${d.mes}</td><td>${d.establecimiento}</td><td>${d.servicio}</td><td>${d.profesional}</td><td>${d.atenciones}</td><td>${d.meta}</td><td>${d.errores}</td><td><span class="badge ${e.clase}">${e.texto}</span></td></tr>`;}).join("");}
